### ISSUE TITLE
Remove or merge in dev submodules

### ISSUE THREAD

**Issue by frimmel** [nemac/data_snapshots#67]
`add_this_dev`: Sets up the `Add This` block which already exists in climate.gov. Should be removed from final version.
`data_snapshot_dev_view_modes`: Defines view modes which already exist in climate.gov. Should be removed from final version.
`data_snapshot_css_dev`: Defines css for Data Snapshot node in the views modes which already exist in climate.gov. Should be merged in.
`dss_views_dev`: Creates pages to view all nodes in the different view modes. Should be removed from final version.
`global_dependencies`: Sets up taxonomies that exist in climate.gov. Should be removed from final version.

**Comment by embeepea** [comment]
I'm not sure I understand what is needed here.   Am I correct in understanding that these are modules that we use in our dss-dev.nemac.org site in order to "fool" our copy of the data snapshots module into thinking that it is running on a full climate.gov site?  So these modules don't need to be present on the real climate.gov site, and they are not a part of the data_snapshots module that we are handing over for deployment to climate.gov, right?  So why is there anything that needs to be done?  Am I missing something?

**Comment by frimmel** [comment]
For the most part nothing needs to be done, however the code in the module `data_snapshot_css_dev` would be useful on the live site and should be merged in.
